version: '3'

services:
  server:
    image: afg-server:2.0
    build:
      context: ./server
      dockerfile: Dockerfile.server
    environment:
      - DB_NAME=afg
      - DB_USER=postgres
      - DB_PASSWORD=0105
      - DB_HOST=db
      - DB_PORT=5432
    container_name: afg-server
    ports:
      - 5000:5000
    depends_on:
      - db

  client:
    image: afg-multi
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: afg-client
    ports:
      - 5173:5173
      - server
    restart: unless-stopped

  db:
    image: postgres
    container_name: AFG_DB
    ports:
      - "5432:5432"
    env_file: .env

networks:
  net:
    driver: bridge