export const CATEGORIES = [
  { id: 1, image: 'Diverse', title: 'Diverse' },
  { id: 2, image: 'Reachstacker', title: 'Reachstacker' },
  { id: 3, image: 'Tractor', title: 'Tractor' },
  { id: 4, image: 'Overslagkraan', title: 'Overslagkraan' },
  { id: 5, image: 'Verreiker', title: 'Verreiker' },
  { id: 6, image: 'Backhoe_Loader', title: 'Backhoe Loaders' },
  { id: 7, image: 'Bulldozers', title: 'Bulldozers' },
  { id: 8, image: 'Wiellader', title: 'Wiellader' },
  { id: 9, image: 'Graders', title: 'Graders' },
  { id: 10, image: 'Generators', title: 'Generators' },
  { id: 11, image: 'Dumper', title: 'Dumper' },
  { id: 12, image: 'Zeef', title: 'Zeef' },
  { id: 13, image: 'Asfalt-Recycler', title: 'Asfalt Recycler' },
  { id: 14, image: 'Bakken', title: 'Bakken' },
  { id: 15, image: 'Skidsteers', title: 'Skidsteers' },
  { id: 16, image: 'Excavator', title: 'Excavators' },
  { id: 17, image: 'Vergruizer', title: 'Vergruizer' },
  { id: 18, image: 'Drills', title: 'Drills' },
  { id: 19, image: 'Asfalteermachine', title: 'Asfalteermachine' },
  { id: 20, image: 'Hamer', title: 'Hamer' },
  { id: 21, image: 'Alle-Machines', title: 'Alle Machines' },
  { id: 22, image: 'Oplegger', title: 'Oplegger' },
  { id: 23, image: 'Rupsgraafmachine', title: 'Rupsgraafmachine' },
  { id: 24, image: 'Rollers', title: 'Rollers' },
  { id: 25, image: 'Compressor', title: 'Compressor' },
  { id: 26, image: 'Asfalt-frees', title: 'Asfalt frees' },
  { id: 27, image: 'Vrachtwagen', title: 'Vrachtwagen' },
  { id: 28, image: 'Band', title: 'Band' },
];
